export const ADD_CLIENTE = 'ADD_CLIENTE';
export const EDIT_CLIENTE = 'EDIT_CLIENTE';
export const DELETE_CLIENTE = 'DELETE_CLIENTE';
export const ADD_MULTI_CLIENTI = 'ADD_MULTI_CLIENTI';
export const TRUNCATE_CLIENTI = 'TRUNCATE_CLIENTI';
